parameters:
  eye_on_hand: true
  freehand_robot_movement: false
  move_group: xarm7
  move_group_namespace: /
  namespace: /xarm_realsense_handeyecalibration_eye_on_hand/
  robot_base_frame: link_base
  robot_effector_frame: link_eef
  tracking_base_frame: camera_color_optical_frame
  tracking_marker_frame: camera_marker
transformation:
  qx: .017
  qy: .0007
  qz: -.725
  qw: .688  
  x: 0.05
  y: 0.03
  z: .03