parameters:
  eye_on_hand: true
  freehand_robot_movement: false
  move_group: xarm7
  move_group_namespace: /
  namespace: /xarm_realsense_handeyecalibration_eye_on_hand/
  robot_base_frame: link_base
  robot_effector_frame: link_eef
  tracking_base_frame: camera_color_optical_frame
  tracking_marker_frame: camera_marker
transformation:
  qw: -0.00225498533906
  qx: -0.00993543411089
  qy: -0.669211594746
  qz: 0.743002048212
  x: 0.0322023424469
  y: 0.0343318434351
  z: -0.0210167210488