# Total planning attempts
max_solutions: 20

# Planning group and link names
arm_group_name: "xarm7"
eef_name: "xarm_gripper"
hand_group_name: "xarm_gripper"
hand_frame: "link_eef"

# Poses
hand_open_pose: "open"
hand_close_pose: "close"
arm_home_pose: "home"

# Scene frames
world_frame: "world"
table_reference_frame: "world"
object_reference_frame: "world"
camera_reference_frame: "world"
# human_reference_frame: "world"
surface_link: "table"

# Environment object
env_name: "<octomap>"



 # Collision object for picking
 # CYLINDER object specifications
spawn_mesh: false #still spawns the model
object_name: "cylinder"
object_dimensions: [0.25, 0.02] # [height, radius]
object_pose: [0.4, -0.25, -0.05, 0, 0, 0]

# Camera collision object
spawn_camera: false
camera_name: "camera"
camera_mesh_file: "package://deep_grasp_task/meshes/camera/kinect.dae"
camera_pose: [0, -0.25, .1, 0, 0, 1.571] # side
# camera_pose: [0.5, 0, 0.7, 0, 1.571, 1.571] # over head

# Table model
spawn_table: true
table_name: "table"
table_dimensions: [2, 2, 0.1]  # [length, width, height]
table_pose: [0, 0, -0.025, 0, 0, 0]

# Box list
box_num: 3
box_name0: "chair"
box_dimensions0: [0.3, .3, .2]  # [length, width, height]
box_pose0: [-0.25, -0.1, 0, 0, 0, 0]

box_name1: "human"
box_dimensions1: [0.5, .5, .25]  # [length, width, height]
box_pose1: [-0.2, 0.4,0, 0, 0, 0]

box_name2: "table2"
box_dimensions2: [.2,.2,.024]
box_pose2: [0, 0, -0.025,0,0,0]

# Gripper grasp frame transform [x,y,z,r,p,y]
grasp_frame_transform: [0, 0, 0.1, 1.571,-4.712, 1.571]

# Place pose [x,y,z,r,p,y]
# place_pose: [0.5, 0.3, 0, 0, 0, 0]
place_pose: [0.6, -0.15, 0, 0, 0, 0]
place_surface_offset: 0.0001 # place offset from table

# Valid distance range when approaching an object for picking
approach_object_min_dist: 0.1
approach_object_max_dist: 0.15

# Valid height range when lifting an object after pick
lift_object_min_dist: 0.01
lift_object_max_dist: 0.1
